version: 2.1
#orbs - reusable packages for our appllication for use
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/docker@2.0.0

#Jobs - set of instructions / functions
jobs:
  build: #Job name
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : |
          echo "Installing depedencies..."
          npm install
  test:
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : |
          echo "Running tests.."
          npm run test
  publish:
    executor: docker/docker 
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: anushadevelopment/education-space
          tag: v1.0.1
      - docker/push:
          image: anushadevelopment/education-space
          tag: v1.0.1
    deploy:
      docker:
        - image: cimg/node:16.10
      steps:
        - setup_remote_docker
        - heroku/install
        - checkout
        - run:
          name: Heroku Container Push
          command:
            heroku container:login
            heroku container:push web -a anusha-su-devops
            heroku container:release web -a anusha-su-devops
# Workflow - defines what sequence will the jobs run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish